config/routes.rb
Crm::Application.routes.draw do

  devise_for :users

  root :to => 'contacts#index'

  resources :charges
  resources :contacts

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :email, :first_name, :last_name, :bill_amount
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :bill_address, :bill_city, :bill_country, :bill_first_name, :bill_last_name, :bill_state, :bill_zip, :email, :item_amount, :item_desc, :item_name, :item_rate, :order_date, :order_no, :payment_type, :phone, :po_num, :product_code, :product_options, :promo_code, :qty, :ship_address, :ship_city, :ship_cost, :ship_country, :ship_first_name, :ship_last_name, :ship_method, :ship_state, :ship_zip, :store, :tax_total, :total_order, :unit_weight

	def self.import(file)
		CSV.foreach(file.path, headers: true) do |row|
		  	@a = row.to_hash
		    puts @a
		    order = Order.create!
		    order.update_attributes(:order_no => @a["ORDER_NO"], :store => @a["STORE_NAME"], 
		    	:order_date => @a["TXN_DT"], :payment_type => @a["PAYMENTMETHOD_REF"], :phone => @a["PHONE"],
		    	:email => @a["EMAIL"], :bill_first_name => @a["BADDR_FIRST_NM"],
		    	:bill_last_name => @a["BADDR_LAST_NM"], :bill_address => @a["BADDR_LINE1"], 
		    	:bill_city => @a["BADDR_CITY"], :bill_state => @a["BADDR_CITY"], :bill_state => @a["BADDR_STATE"],
		    	:bill_zip => @a["BADDR_ZIP"], :bill_country => @a["BADDR_COUNTRY"], 
		    	:ship_first_name => @a["SADDR_FIRST_NM"], :ship_last_name => @a["SADDR_LAST_NM"],
		    	:ship_address => @a["SADDR_LINE1"], :ship_city => @a["SADDR_CITY"], 
		    	:ship_zip => @a["SADDR_ZIP"], :ship_country => @a["SADDR_COUNTRY"],
		    	:po_num => @a["PO_NUMBER"], :ship_method => @a["SHIP_METHOD_REF"],
		    	:tax_total => @a["TAX1_TOTAL"], :ship_cost => @a["TOTAL_SHIP_COST"],
		    	:total_order => @a["TOTAL_ORDER_AMT"], :item_name => @a["ITEM_NAME"],
		    	:item_desc => @a["ITEM_DESC"], :qty => @a["ITEM_QUANTITY"], :item_rate => @a["ITEM_RATE"], 
		    	:item_amount => @a["ITEM_AMOUNT"], :unit_weight => @a["ITEM_UNIT_WEIGHT_LBS"], 
		    	:product_options => @a["PRODUCT_WITH_OPTIONS"], :product_code => @a["PRODUCT_CODE"],
		    	:promo_code => @a["PROMO_CODE"])
	  	end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	def new
	end

	def create
	  # Amount in cents
	  @contact = Contact.find(1)
	  @amount = @contact.bill_amount

	  customer = Stripe::Customer.create(
	    :email => 'example@stripe.com',
	    :card  => params[:stripeToken]
	  )

	  charge = Stripe::Charge.create(
	    :customer    => customer.id,
	    :amount      => @amount,
	    :description => 'Rails Stripe customer',
	    :currency    => 'usd'
	  )

	rescue Stripe::CardError => e
	  flash[:error] = e.message
	  redirect_to charges_path
	end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @contact = Contact.all
  end

  def show
    @contact = Contact.find(params[:id])
  end
  
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    if @contact.save
        flash[:success] = "Successfully assigned PO!"
        redirect_to contacts_path
    else
      redirect_to (:back)
    end
  end
  
  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to raw_companies_path }
    end
  end

  def edit
    @contact = Contact.find(params[:id]) 
  end

    def update
    @contact = Contact.where(:id => params[:id]).first

      respond_to do |format|
        if @contact.update_attributes(params[:contact])
          format.html { redirect_to contacts_path, :notice => 'Contact was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @contact.errors, :status => :unprocessable_entity }
        end
      end
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

	def import
	  Order.import(params[:file])
	  redirect_to root_url, notice: "Orders imported."
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/charges/create.html.erb
<% last = Contact.order("updated_at").last %>
<h2>Thanks, you charged <strong><%= last.bill_amount %></strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/v2/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"></script>
<% end %>

app/views/contacts/edit.html.erb
<div class="hero-unit">
	<h2>Edit Contact</h2>
	<br>
	<%= simple_form_for(@contact, :html => {:class => 'form-horizontal' }) do |f| %>
		<%= f.input :first_name %>
		<%= f.input :last_name %>
		<%= f.input :email %>
		<%= f.input :bill_amount %>
		<%= f.submit %>
	<% end %>
</div>

app/views/contacts/index.html.erb
<h1>Your Contacts</h1>
<br>
<div class="hero-unit">
	<td><%= link_to "New Contact", new_contact_path, 
					                        class: "btn btn-primary btn-success" %></td>
	<br><br>
	<table class="table table-bordered">
		<thead>
			<tr>
				<th>View Detail</th>
	  			<th>First Name</th>
	  			<th>Last Name</th>
	  			<th>Email</th>
	  			<th>Monthly Bill</th>
	  		</tr>
	  	</thead>
	  	<% Contact.all.each do |x| %>
		  	<tbody>
		  		<tr>
		  			<td><%= link_to "View", contact_path(x), 
					                        class: "btn btn-primary btn-primary" %>
					<%= link_to "Edit", edit_contact_path(x), 
					                        class: "btn btn-primary btn-primary" %></td>
			  		<td><%= x.first_name %></td>
			  		<td><%= x.last_name %></td>
			  		<td><%= x.email %></td>
			  		<td><%= number_to_currency(x.bill_amount) %></td>
			  	</tr>
		  	</tbody>
		<% end %>
	</table>
</div>

app/views/contacts/new.html.erb
<div class="center hero-unit">
  <%= simple_form_for(@contact) do |f| %>
	  <%= f.input :first_name %>
	  <%= f.input :last_name %>
	  <%= f.input :email %>
	  <%= f.submit %>
  <% end %>
</div>

app/views/contacts/show.html.erb
<div class="hero-unit">
	<%= @contact.first_name %>
	<%= @contact.last_name %>
	<%= @contact.email %>


<%= form_tag charges_path do %>
  <article>
    <label class="amount">
      <span>Amount: <%= @contact.bill_amount %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/v2/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="<%= @contact.bill_amount %>"></script>
<% end %>

</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">

      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> 
        <span class="icon-bar"></span> 
        <span class="icon-bar"></span> 
        <span class="icon-bar"></span>        
      </a>


      <nav>
        <div class="nav-collapse">
          <%=link_to(image_tag("ball.png", :size => "60x60", :alt=> "Logo"),
             root_path, :title=>"Return Home", :class=>"logo") %>
          <ul class="nav pull-right"> 
            <li><h3><%= link_to "Contacts", contacts_path %></h3></li> 
            <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>    
            <li><h3><%= link_to "Leads", contacts_path %></h3></li>   
            <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li> 
            <li><h3><%= link_to "To Do's", contacts_path %></h3></li> 
            <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>
            <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>
            <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>
            <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>

            <li class="dropdown">
              <div class="nav-logins">
              <% if user_signed_in? %>
                
                  <h5><%= link_to 'Logged in' %>
                 



 
                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   <%= link_to "Logout", destroy_user_session_path, method: :delete %></h5>
                
              <% else %>  
                <li> <%= link_to "Sign up", new_user_registration_path %> |</li>
                <li> <%= link_to "Login", new_user_session_path %></li>
              <% end %> 
            </div>
            </li> 
          </ul>
        </div>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NanaConvert</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
        <%= msg  %>
      </div>
    <% end %>

<%= render 'layouts/header' %>

<%= yield %>

</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/orders/index.html.erb
<h2>Import</h2>
<%= form_tag import_orders_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

<div class="hero-unit">
	<table class="table table-bordered">
		<thead>
			<tr>
	  			<th>Order Number</th>
	  			<th>Store</th>
	  			<th>Order Date</th>
	  		</tr>
	  	</thead>
	  	<% Order.all.each do |x| %>
		  	<tbody>
		  		<tr>
			  		<td><%= x.order_no %></td>
			  		<td><%= x.store %></td>
			  		<td><%= x.order_date %></td>
			  	</tr>
		  	</tbody>
		<% end %>
	</table>
</div>

app/views/static_pages/index.html.erb
<h1>Index Page</h1>